name: "Delegate Compute"
description: "UbiquiBot Delegated Compute Action"
outputs:
  result: # id of output
    description: "The result of a event handler"
    value: ${{ steps.mainHandler.outputs.result}}
runs:
  using: "composite"
  steps:
    - run: cd ${{ github.action_path }}
      shell: bash
    - run: pnpm install
      shell: bash
    - run: pnpm start
      shell: bash
      id: mainHandler