name: Delegated Compute

on:
  workflow_dispatch:
    inputs:
      stateId:
        required: true
      eventName:
        required: true
      eventPayload:
        required: true
      settings:
        required: true
      authToken:
        required: true
      ref:
        required: true

jobs:
  run:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}

      - name: Echo inputs
        run: echo ${{ inputs.settings }}

      - name: Calling action
        uses: ./
        with:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
