name: Delegated Compute

on:
  workflow_dispatch:
    inputs:
      stateId:
        required: true
      eventName:
        required: true
      eventPayload:
        required: true
      settings:
        required: true
      authToken:
        required: true
      ref:
        required: true

jobs:
  run:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}

      - name: Echo inputs
        run: echo ${{ inputs.settings }}

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install Bun
        run: npm install -g bun

      - name: Generate Supabase Types
        run: |
          yarn install
          yarn run "supabase:generate:remote"

      - name: Calling action
        uses: ./
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
